language: node_js
node_js:
  - stable
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
before_install:
  - set -e
  # Add ssh key w/ write permission for `as24-custom-events` repo
  - openssl aes-256-cbc -K $encrypted_ab46abe2afd1_key -iv $encrypted_ab46abe2afd1_iv -in travis_ci_rsa.enc -out ./travis_ci_rsa -d
  - chmod 600 travis_ci_rsa
  - eval `ssh-agent -s`
  - ssh-add travis_ci_rsa
install:
  - yarn install
  - yarn global add codecov
script:
  - yarn run test
  - yarn run build
after_success:
  - codecov
  - |
    # Check if we need to do SEMVER bump based on commit's parent PR labels
    # - only run for master branch we don't want to release PRs and other branches
    # - only run on non-tagged releases, this will bump the version, tag, commit & push back to github
    if [ "$TRAVIS_PULL_REQUEST" != "true" ] && [ -z "$TRAVIS_TAG" ] && [ "$TRAVIS_BRANCH" == "master" ]; then 
      echo "Travis commit: $TRAVIS_COMMIT"
      SEMVER_BUMP=$(./semver_from_pr_labels.sh $TRAVIS_COMMIT 2>/dev/null)
      echo $SERVER_BUMP
      if [ -z "$SERVER_BUMP" ]; then
        echo "Bumping package version for $SEMVER_BUMP release and pushing tag to github"
        yarn version --new-version $SEMVER_BUMP
        git push --follow-tags
      fi
    fi
deploy:
  - provider: npm
    email: '#AS24-Web-Experience-Team-ds@scout24.com'
    skip_cleanup: true
    api_key:
      secure: o7ISixwUP0ld20BDuQlKwXNTB0NM7flq38YUZWVRl8PFwekb/qSwzK6ZJWSQ5HstodxofVotLDXmHcjAfpozp5FHMKOLd9nEajcpURaSp3YtZm5FX7vZKXG5EBj8wEJ8B6UYuMMYhjfY1U35xc0DqMggGBVj58k31c1LcRMrJzX/xAfATsOnjNKGXuzU6nPLrGJywfTWQk3mLhjfNWq6ZW54CCY4A5CzsFWYTjHa4OGCFpZ7KNyG+bIs/J/UuHl86exdL8S54GDR8BtYe2Cp852HsBxpDUM1ZjvNcGIT+eQc3H/sNouRt5t74cTD+/9GDidmgFf7YI4jkJLO2mvT2PVv43GYyI26pAH9BJtTXLxjwSsht1NxWpGajmDIJWS9D0aVkfcKuTd2+JryYqIuxCLBTbgRPliaiPCf8a4w6RPYC4t0ICAtmFr5KhlcTkUzUiAZHsu+HaO6VgOzb0YKepyS3wNPVfXA0oAFgTBoYaoSFA990oRLop/2C+PVFbGrvYod8vACD6KjnLMm6bLi14iYxDDcPAmTqMn36RII3Wo4HBwYdwOPBC1wMsnTP5Rp+y5dJpJTw1N5qe+Wb7wdxEqwMX04zEoPI6puQBR9q4I90LxlUuKRo7b8wnYEILyzxVkURDriU7mCL1+m0AI+eSZ98rvt+RWvPCcie6e3h68=
    on:
      tags: true
      repo: Scout24/as24-custom-events
      branch: master
  - provider: releases
    skip_cleanup: true
    file_glob: true
    file:
      - './dist/**/*'
    on:
      tags: true
      repo: Scout24/as24-custom-events
      branch: master
